pub_rate: 1.0 # Optional
base_path: '' # Optional, prepended to all diagnostic output
analyzers:
  computers:
    type: AnalyzerGroup
    path: Computers
    analyzers:
      pc1:
        type: diagnostic_aggregator/GenericAnalyzer
        path: pc1
        contains: 'pc1'

  sensors:
    type: AnalyzerGroup
    path: Sensors
    analyzers:
      laser_rear:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Rear
        contains: 'laser_rear'
      laser_front:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Front
        contains: 'laser_front'
      stereo_left:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Stereo (Left)
        startswith: ['stereo/left/color_camera']
      stereo_right:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Stereo (Right)
        contains: right
        startswith: ['stereo/right/color_camera']

  motors:
    type: AnalyzerGroup
    path: Actuators
    analyzers:
      torso:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Torso
        contains: 'torso_controller'
      base:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Base
        contains: 'base_controller'
