#Parameters for Relayboard

#Device on which relayboard is attached
ComPort: /dev/ttyUSB0
relayboard_timeout: 2.0
requestRate: 25

#Define the version of the protocol used by the Relayboard (the type of lcd interface)
protocol_version: 0 

#TODO: relayboard_voltage_offset: 2.6

